export const products = [
  // Apple Phones
  {
    id: 1,
    name: "iPhone 14 Pro",
    category: "Apple",
    price: 999,
    imageUrl: "14pro.png",
    rating: 5,
  },
  {
    id: 2,
    name: "iPhone 15",
    category: "Apple",
    price: 699,
    imageUrl: "15.png",
    rating: 4,
  },
  {
    id: 3,
    name: "iPhone 14",
    category: "Apple",
    price: 649,
    imageUrl: "14.png",
    rating: 3,
  },
  {
    id: 4,
    name: "iPhone 15 Pro",
    category: "Apple",
    price: 1049,
    imageUrl: "15pro.png",
    rating: 4,
  },
  {
    id: 5,
    name: "iPhone 16",
    category: "Apple",
    price: 799,
    imageUrl: "16.png",
    rating: 4.5,
  },
  {
    id: 6,
    name: "iPhone 16 Pro",
    category: "Apple",
    price: 1299,
    imageUrl: "16pro.png",
    rating: 4.5,
  },

  // Samsung Phones
  {
    id: 7,
    name: "King Size Bed",
    category: "Samsung",
    price: 299,
    imageUrl: "s22-ultra.png",
    rating: 5,
  },
  {
    id: 8,
    name: "Queen Size Bed",
    category: "Samsung",
    price: 249,
    imageUrl: "s24+.png",
    rating: 5,
  },
  {
    id: 9,
    name: "Modern Bed Frame",
    category: "Samsung",
    price: 399,
    imageUrl: "s22.png",
    rating: 3,
  },
  {
    id: 10,
    name: "Platform Bed",
    category: "Samsung",
    price: 349,
    imageUrl: "s21+.png",
    rating: 2,
  },
  {
    id: 11,
    name: "Sleigh Bed",
    category: "Samsung",
    price: 459,
    imageUrl: "s21fe.png",
    rating: 5,
  },
  {
    id: 12,
    name: "Sleigh Bed",
    category: "Samsung",
    price: 459,
    imageUrl: "s20fe.png",
    rating: 5,
  },
  {
    id: 13,
    name: "Sleigh Bed",
    category: "Samsung",
    price: 459,
    imageUrl: "m55.png",
    rating: 5,
  },
  {
    id: 14,
    name: "Sleigh Bed",
    category: "Samsung",
    price: 459,
    imageUrl: "a55.png",
    rating: 5,
  },
  {
    id: 15,
    name: "Sleigh Bed",
    category: "Samsung",
    price: 459,
    imageUrl: "a53.png",
    rating: 5,
  },
  {
    id: 16,
    name: "Sleigh Bed",
    category: "Samsung",
    price: 459,
    imageUrl: "sf15.png",
    rating: 5,
  },

  // Huawei Phones
  {
    id: 17,
    name: "Luxury Sofa",
    category: "Huawei",
    price: 499,
    imageUrl: "pura70.png",
    rating: 4,
  },
  {
    id: 18,
    name: "Compact Sofa",
    category: "Huawei",
    price: 399,
    imageUrl: "nova12.png",
    rating: 5,
  },
  {
    id: 19,
    name: "L-shaped Sofa",
    category: "Huawei",
    price: 699,
    imageUrl: "nova11.png",
    rating: 4,
  },
  {
    id: 20,
    name: "Sofa with Chaise",
    category: "Huawei",
    price: 549,
    imageUrl: "nova-y.png",
    rating: 5,
  },
  {
    id: 21,
    name: "Sectional Sofa",
    category: "Huawei",
    price: 799,
    imageUrl: "nova12-pro.png",
    rating: 3.6,
  },
  {
    id: 22,
    name: "Sectional Sofa",
    category: "Huawei",
    price: 799,
    imageUrl: "p70.png",
    rating: 3.6,
  },
  {
    id: 23,
    name: "Sectional Sofa",
    category: "Huawei",
    price: 799,
    imageUrl: "p60.png",
    rating: 3.6,
  },

  // Oneplus Phones
  {
    id: 24,
    name: "Modern Lamp",
    category: "Oneplus",
    price: 49,
    imageUrl: "12.png",
    rating: 5,
  },
  {
    id: 25,
    name: "Classic Lamp",
    category: "Oneplus",
    price: 59,
    imageUrl: "10.png",
    rating: 4,
  },
  {
    id: 26,
    name: "Wooden Table Lamp",
    category: "Oneplus",
    price: 69,
    imageUrl: "ace-2v.png",
    rating: 3,
  },
  {
    id: 27,
    name: "Industrial Floor Lamp",
    category: "Oneplus",
    price: 89,
    imageUrl: "nord-ce3.png",
    rating: 5,
  },
  {
    id: 28,
    name: "Vintage Desk Lamp",
    category: "Oneplus",
    price: 79,
    imageUrl: "ace3-pro.png",
    rating: 4,
  },
  {
    id: 29,
    name: "Vintage Desk Lamp",
    category: "Oneplus",
    price: 79,
    imageUrl: "nord4.png",
    rating: 4,
  },
];
