export const products = [
  // Apple Phones
  {
    id: 1,
    name: "iPhone 14 Pro",
    category: "Apple",
    price: 999,
    imageUrl: "14pro.png",
    rating: 5,
  },
  {
    id: 2,
    name: "iPhone 15",
    category: "Apple",
    price: 699,
    imageUrl: "15.png",
    rating: 4,
  },
  {
    id: 3,
    name: "iPhone 14",
    category: "Apple",
    price: 649,
    imageUrl: "14.png",
    rating: 3,
  },
  {
    id: 4,
    name: "iPhone 15 Pro",
    category: "Apple",
    price: 1049,
    imageUrl: "15pro.png",
    rating: 4,
  },
  {
    id: 5,
    name: "iPhone 16",
    category: "Apple",
    price: 799,
    imageUrl: "16.png",
    rating: 4.5,
  },
  {
    id: 6,
    name: "iPhone 16 Pro",
    category: "Apple",
    price: 1299,
    imageUrl: "16pro.png",
    rating: 4.5,
  },

  // Samsung Phones
  {
    id: 7,
    name: "Galaxy S22 Ultra",
    category: "Samsung",
    price: 1299,
    imageUrl: "s22-ultra.png",
    rating: 5,
  },
  {
    id: 8,
    name: "Galaxy S24 Plus",
    category: "Samsung",
    price: 1099,
    imageUrl: "s24+.png",
    rating: 5,
  },
  {
    id: 9,
    name: "Galaxy S22",
    category: "Samsung",
    price: 799,
    imageUrl: "s22.png",
    rating: 3,
  },
  {
    id: 10,
    name: "Galaxy S21 Plus",
    category: "Samsung",
    price: 449,
    imageUrl: "s21+.png",
    rating: 2,
  },
  {
    id: 11,
    name: "Galaxy S21 FE",
    category: "Samsung",
    price: 559,
    imageUrl: "s21fe.png",
    rating: 5,
  },
  {
    id: 12,
    name: "Galaxy S20 FE",
    category: "Samsung",
    price: 459,
    imageUrl: "s20fe.png",
    rating: 5,
  },
  {
    id: 13,
    name: "Galaxy M55",
    category: "Samsung",
    price: 299,
    imageUrl: "m55.png",
    rating: 5,
  },
  {
    id: 14,
    name: "Galaxy A55",
    category: "Samsung",
    price: 359,
    imageUrl: "a55.png",
    rating: 5,
  },
  {
    id: 15,
    name: "Galaxy A53",
    category: "Samsung",
    price: 259,
    imageUrl: "a53.png",
    rating: 5,
  },
  {
    id: 16,
    name: "Galaxy F15",
    category: "Samsung",
    price: 289,
    imageUrl: "f15.png",
    rating: 5,
  },

  // Huawei Phones
  {
    id: 17,
    name: "Huawei Pura 70",
    category: "Huawei",
    price: 1299,
    imageUrl: "pura70.png",
    rating: 4,
  },
  {
    id: 18,
    name: "Huawei Nova 12",
    category: "Huawei",
    price: 399,
    imageUrl: "nova12.png",
    rating: 5,
  },
  {
    id: 19,
    name: "Huawei Nova 11",
    category: "Huawei",
    price: 349,
    imageUrl: "p60.png",
    rating: 4,
  },
  {
    id: 20,
    name: "Huawei Nova Y",
    category: "Huawei",
    price: 549,
    imageUrl: "nova-y.png",
    rating: 5,
  },
  {
    id: 21,
    name: "Huawei Nova 12 Pro",
    category: "Huawei",
    price: 449,
    imageUrl: "nova12-pro.png",
    rating: 3.6,
  },
  {
    id: 22,
    name: "Huawei P70",
    category: "Huawei",
    price: 799,
    imageUrl: "p70.png",
    rating: 3.6,
  },
  {
    id: 23,
    name: "Huawei P60",
    category: "Huawei",
    price: 749,
    imageUrl: "p60.png",
    rating: 3.6,
  },

  // Oneplus Phones
  {
    id: 24,
    name: "Oneplus 12",
    category: "Oneplus",
    price: 849,
    imageUrl: "12.png",
    rating: 5,
  },
  {
    id: 25,
    name: "Oneplus Ace 2V",
    category: "Oneplus",
    price: 249,
    imageUrl: "ace-2v.png",
    rating: 3,
  },
  {
    id: 26,
    name: "Oneplus Nord CE 3",
    category: "Oneplus",
    price: 389,
    imageUrl: "nord-ce3.png",
    rating: 5,
  },
  {
    id: 27,
    name: "Oneplus Ace 3 Pro",
    category: "Oneplus",
    price: 479,
    imageUrl: "ace3-pro.png",
    rating: 4,
  },
  {
    id: 28,
    name: "Oneplus Nord 4",
    category: "Oneplus",
    price: 579,
    imageUrl: "nord4.png",
    rating: 4,
  },
];
